// <auto-generated />
using System;
using AnalyticsDashboard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnalyticsDashboard.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250919091138_AddTrafficLogsTable")]
    partial class AddTrafficLogsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("AnalyticsDashboard.Data.TrafficLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocalIPs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OtherIPs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceDomain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalClicks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UniqueClicks")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TrafficLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
